[package]
name = "diy-sonos"
version = "1.0.0"
description = "DIY Sonos Desktop"
authors = ["jeffcottj"]
edition = "2021"
rust-version = "1.77"

[lib]
name = "diy_sonos_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-updater = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.9"
thiserror = "2"
anyhow = "1"
tokio = { version = "1", features = ["full"] }
russh = { version = "0.44", features = [] }
russh-sftp = { version = "2", features = [] }
mdns-sd = "0.13"
ssh-key = { version = "0.6", features = ["ed25519"] }
regex = "1"
sha2 = "0.10"
data-encoding = "2"
rand = "0.8"
[dev-dependencies]
tempfile = "3"
